name: Discord Clone CI

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Build and lint
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile
          yarn build
          yarn lint
